header:
  license:
    spdx-id: AGPL-3.0-or-later
    copyright-owner: Genome Research Ltd
    content: |
      Copyright (c) 2014-2021 Genome Research Ltd

      Author: CASM/Cancer IT <cgphelp@sanger.ac.uk>

      This file is part of cgpPindel.

      This program is free software: you can redistribute it and/or modify
      it under the terms of the GNU Affero General Public License as
      published by the Free Software Foundation, either version 3 of the
      License, or (at your option) any later version.

      This program is distributed in the hope that it will be useful,
      but WITHOUT ANY WARRANTY; without even the implied warranty of
      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
      GNU Affero General Public License for more details.

      You should have received a copy of the GNU Affero General Public License
      along with this program.  If not, see <https://www.gnu.org/licenses/>.

      1. The usage of a range of years within a copyright statement contained within
      this distribution should be interpreted as being equivalent to a list of years
      including the first and last year specified and all consecutive years between
      them. For example, a copyright statement that reads ‘Copyright (c) 2005, 2007-
      2009, 2011-2012’ should be interpreted as being identical to a statement that
      reads ‘Copyright (c) 2005, 2007, 2008, 2009, 2011, 2012’ and a copyright
      statement that reads ‘Copyright (c) 2005-2012’ should be interpreted as being
      identical to a statement that reads ‘Copyright (c) 2005, 2006, 2007, 2008,
      2009, 2010, 2011, 2012’.

    pattern: |
      Copyright \(c\) \d+ .+

      Author: .+

      This file is part of .+

      This program is free software: you can redistribute it and/or modify
      it under the terms of the GNU Affero General Public License as
      published by the Free Software Foundation, either version 3 of the
      License, or \(at your option\) any later version.

      You should have received a copy of the GNU Affero General Public License
      along with this program.  If not, see <https://www.gnu.org/licenses/>.

      1. The usage of a range of years within a copyright statement contained within
      this distribution should be interpreted as being equivalent to a list of years
      including the first and last year specified and all consecutive years between
      them. For example, a copyright statement that reads ‘Copyright \(c\) 2005, 2007-
      2009, 2011-2012’ should be interpreted as being identical to a statement that
      reads ‘Copyright \(c\) 2005, 2007, 2008, 2009, 2011, 2012’ and a copyright
      statement that reads ‘Copyright \(c\) 2005-2012’ should be interpreted as being
      identical to a statement that reads ‘Copyright \(c\) 2005, 2006, 2007, 2008,
      2009, 2010, 2011, 2012’.

  paths:
    - '**'

  paths-ignore:
    - '.circleci'
    - '.coveragerc'
    - '.dockerignore'
    - '.gitignore'
    - '.pre-commit-config.yaml'
    - 'CHANGES.md'
    - 'Dockerfile'
    - 'LICENSE'
    - 'pyproject.toml'
    - 'README.md'
    - '**/*.yaml'
    - 'tests/data/**/*'
    - '**/*.egg-info/PKG-INFO'
    - '.pytest_cache/'
    - 'build/'
    - 'MANIFEST.in'
    - 'tests/htmlcov/'
    - '.eggs/'
    - 'c++/*.cpp' # not ours, distributed via agreement
    - 'perl/t/'
    - 'perl/rules/'
    - 'perl/pm_to_blib'
    - 'perl/blib/'
    - 'perl/MANIFEST*'
    - 'perl/MYMETA*'
    - '.github/'
    - 'INSTALL'
    - 'Makefile'

  comment: on-failure
