notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

env:
 - CC=gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install -qy build-essential autoconf bsdtar time curl libcurl4-openssl-dev nettle-dev zlib1g-dev libncurses5-dev libpstreams-dev unzip libpng12-dev libexpat1-dev libgoogle-perftools-dev lsof libbz2-dev liblzma-dev libgnutls-dev libtasn1-6-dev p11-kit libxml2-dev libgd-dev psmisc

#before_install:
#  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157

# addons:
#  apt:
#   update: true
#   packages:
#    - build-essential
#    - autoconf
#    - bsdtar
#    - time
#    - curl
#    - libcurl4-openssl-dev
#    - nettle-dev
#    - zlib1g-dev
#    - libncurses5-dev
#    - libpstreams-dev
#    - unzip
#    - libpng12-dev
#    - libexpat1-dev
#    - libgoogle-perftools-dev
#    - lsof
#    - libbz2-dev
#    - liblzma-dev
#    - libgnutls-dev
#    - libtasn1-6-dev
#    - p11-kit
#    - libxml2-dev
#    - libgd-dev
#    - psmisc

install: true

language: perl

perl:
 - "5.22-shrplib"

script:
 - set -e
 - export PATH=$HOME/install/bin:$HOME/install/biobambam2/bin:$PATH
 - git clone --depth 1 --single-branch --branch develop https://github.com/cancerit/cgpBigWig.git
 - cd cgpBigWig
 - ./setup.sh $HOME/PCAP-opt
 - cd ../
 - git clone --depth 1 --single-branch --branch develop https://github.com/cancerit/PCAP-core.git
 - cd PCAP-core
 - ./setup.sh $HOME/PCAP-opt
 - cd ../
 - git clone --depth 1 --single-branch --branch dev https://github.com/cancerit/cgpVcf.git
 - cd cgpVcf
 - ./setup.sh $HOME/PCAP-opt
 - cd ../
 - ./setup.sh $HOME/PCAP-opt
