# 1. Set your default branch to develop
# 2. In circleci project settings->advanced set:
#    - GitHub Status Updates (this should be on already)
#    - Only build pull requests
#    - Auto-cancel redundant builds
#    - Free and Open Source (this should be on already)

version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: quay.io/wtsicgp/cgppindel
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            set -e
            BRANCH_OR_TAG="${CIRCLE_TAG:-$CLEAN_BRANCH}"
            CLEAN_BRANCH=$(echo $BRANCH_OR_TAG | tr / -)
            docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASSWORD"
            docker login -u "$QUAYIO_USER" -p "$QUAYIO_PASSWORD" quay.io
            docker build -t $IMAGE_NAME:$CLEAN_BRANCH .
            echo 'Verify program(s) from each inherited base image - cgpbigwig'
            docker run -t --rm $IMAGE_NAME:$CLEAN_BRANCH bwjoin --version
            echo 'Verify program(s) from each inherited base image - pcap-core'
            docker run -t --rm $IMAGE_NAME:$CLEAN_BRANCH bwa_mem.pl -version
            docker run -t --rm $IMAGE_NAME:$CLEAN_BRANCH bammarkduplicates2 --version
            docker run -t --rm $IMAGE_NAME:$CLEAN_BRANCH samtools --version
            docker run -t --rm $IMAGE_NAME:$CLEAN_BRANCH bash -c 'bwa 2>&1 | grep Version'
            echo 'Verify program(s) from this repo'
            docker run -t --rm $IMAGE_NAME:$CLEAN_BRANCH pindel.pl --version
            docker run -t --rm $IMAGE_NAME:$CLEAN_BRANCH pindel_input_gen.pl --version
            docker run -t --rm $IMAGE_NAME:$CLEAN_BRANCH pindel_2_combined_vcf.pl --version
            docker run -t --rm $IMAGE_NAME:$CLEAN_BRANCH FlagVcf.pl --version
            docker run -t --rm $IMAGE_NAME:$CLEAN_BRANCH pindel_merge_vcf_bam.pl --version
            docker run -t --rm $IMAGE_NAME:$CLEAN_BRANCH pindel_np_from_vcf.pl --version
            docker run -t --rm $IMAGE_NAME:$CLEAN_BRANCH pindel_germ_bed.pl --version
            docker run -t --rm $IMAGE_NAME:$CLEAN_BRANCH which pindel
            docker run -t --rm $IMAGE_NAME:$CLEAN_BRANCH which filter_pindel_reads
            if [ "$CIRCLE_TAG" = "$BRANCH_OR_TAG" ]; then
              echo 'Pushing image'
              docker push $IMAGE_NAME:$CLEAN_BRANCH
            else
              echo "I am not a tag so not pushing image"
            fi

workflows:
  version: 2.1
  build_test:
    jobs:
      - build:
          context:
            - dockerhub-casmservice
            - quayio-casmservice
          filters:
            tags:
              only: /.+/


# # Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
# version: 2.1

# workflows:
#   build:
#     jobs:
#       - build:
#           context:
#             - dockerhub-casmservice
#       - publish:
#           context:
#             - quayio-casmservice

# jobs:
#  build:
#    machine: true
#    steps:
#      - checkout
#       # build the image from our area, use docker login to protect against future rate-limiting
#      - run: |
#           set -e
#           echo $CIRCLE_BRANCH
#           docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
#           docker build -t quay.io/wtsicgp/cgppindel:$CIRCLE_BRANCH .
#           docker images | grep -c cgppindel
#           echo 'Verify program(s) from each inherited base image - dockstore-cgpbigwig'
#           docker run -t --rm quay.io/wtsicgp/cgppindel:$CIRCLE_BRANCH bwjoin --version
#           echo 'Verify program(s) from each inherited base image - dockstore-cgpmap'
#           docker run -t --rm quay.io/wtsicgp/cgppindel:$CIRCLE_BRANCH bwa_mem.pl -version
#           docker run -t --rm quay.io/wtsicgp/cgppindel:$CIRCLE_BRANCH bammarkduplicates2 --version
#           docker run -t --rm quay.io/wtsicgp/cgppindel:$CIRCLE_BRANCH samtools --version
#           docker run -t --rm quay.io/wtsicgp/cgppindel:$CIRCLE_BRANCH bash -c 'bwa 2>&1 | grep Version'
#           echo 'Verify program(s) from this repo'
#           docker run -t --rm quay.io/wtsicgp/cgppindel:$CIRCLE_BRANCH pindel.pl --version
#           docker run -t --rm quay.io/wtsicgp/cgppindel:$CIRCLE_BRANCH pindel_input_gen.pl --version
#           docker run -t --rm quay.io/wtsicgp/cgppindel:$CIRCLE_BRANCH pindel_2_combined_vcf.pl --version
#           docker run -t --rm quay.io/wtsicgp/cgppindel:$CIRCLE_BRANCH FlagVcf.pl --version
#           docker run -t --rm quay.io/wtsicgp/cgppindel:$CIRCLE_BRANCH pindel_merge_vcf_bam.pl --version
#           docker run -t --rm quay.io/wtsicgp/cgppindel:$CIRCLE_BRANCH pindel_np_from_vcf.pl --version
#           docker run -t --rm quay.io/wtsicgp/cgppindel:$CIRCLE_BRANCH pindel_germ_bed.pl --version
#           docker run -t --rm quay.io/wtsicgp/cgppindel:$CIRCLE_BRANCH which pindel
#           docker run -t --rm quay.io/wtsicgp/cgppindel:$CIRCLE_BRANCH which filter_pindel_reads

#      ## deploy the image
#      #- run: docker push company/app:$CIRCLE_BRANCH
